version: '3.8'  # specify docker-compose version
services:    
  mongodb: # name of the database service
    image: mongo:3.2.6  
    ports:
      - "27017:27017"  
  mongo_seed:
    image: mongo:3.2.6 
    links: 
      - mongodb   
    volumes: 
      - ./mongo-seed:/mongo-seed 
    command:
      /mongo-seed/import.sh

  express: #name of the banckend service
    build: ./backend
    ports:
      - "7000:7000" 
    container_name: seeker-srv
    links:
      - mongodb
      
  angular: # name of the front service
    build: ./frontend 
    ports:
      - "4200:4200" 
    container_name: seeker-cli 




 
        # environment: 
        #   - MONGO_INITDB_ROOT_USERNAME:productListUser
        #   - MONGO_INITDB_ROOT_PASSWORD:productListPassword
        #   - MONGO_INITDB_DATABASE:promotions   
        # # command: 
        # #   /products-db/database/import.sh     
        # volumes: 
        #   - $PWD/products-db/database:/database 
        # command: 
        #   /database/import.sh        